version: '3.8'

services:
  user_app:
    build: ./src/users
    container_name: user_app
    ports:
      - "5000:5000"
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_HOST=user_db
      - DB_NAME=users_db
      - PYTHONUNBUFFERED=1
    networks:
      - user_net
  user_db:
    image: postgres:16-alpine
    container_name: user_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data_users:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d users_db" ]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - user_net
networks:
  user_net:
    driver: bridge
    name: user_net
volumes:
  postgres_data_users: