INSERT INTO products (name, description, cetegory, price, amount) VALUES
('Laptop Gamer', 'Laptop potente con tarjeta gráfica RTX 4060.', 'Electronics', 1800, 25),
('Mouse Inalámbrico', 'Mouse ergonómico con conexión Bluetooth.', 'Accessories', 35, 100),
('Teclado Mecánico', 'Teclado RGB con switches mecánicos.', 'Accessories', 120, 50),
('Monitor 27” 4K', 'Monitor de alta resolución para diseñadores.', 'Electronics', 500, 30),
('Silla Gamer', 'Silla ergonómica con soporte lumbar.', 'Furniture', 250, 40),
('Auriculares Bluetooth', 'Auriculares inalámbricos con cancelación de ruido.', 'Accessories', 150, 60),
('Smartphone Pro', 'Teléfono con pantalla OLED y 128GB de almacenamiento.', 'Electronics', 900, 35),
('Tablet 10”', 'Tablet con pantalla Full HD y 64GB de almacenamiento.', 'Electronics', 350, 45),
('Disco SSD 1TB', 'Unidad de almacenamiento SSD NVMe de alta velocidad.', 'Storage', 200, 55),
('Tarjeta Gráfica RTX 4070', 'GPU potente para gaming y diseño.', 'Electronics', 700, 20),
('Procesador i9 13th Gen', 'CPU de última generación para alto rendimiento.', 'Components', 600, 15),
('Placa Madre Z790', 'Placa base compatible con procesadores Intel de 13ª generación.', 'Components', 300, 25),
('Memoria RAM 32GB', 'Módulo de RAM DDR5 de alto rendimiento.', 'Components', 150, 40),
('Fuente de Poder 750W', 'Fuente certificada 80 Plus Gold.', 'Components', 120, 30),
('Gabinete Gamer', 'Gabinete con diseño moderno y refrigeración avanzada.', 'Components', 100, 35),
('Impresora Multifuncional', 'Impresora con escáner y WiFi.', 'Office', 200, 50),
('Router WiFi 6', 'Router con conexión de alta velocidad y gran alcance.', 'Networking', 180, 45),
('Cámara Web 1080p', 'Cámara para videollamadas con micrófono integrado.', 'Accessories', 80, 70),
('MicroSD 256GB', 'Tarjeta de memoria de alta velocidad.', 'Storage', 50, 100),
('Disco Externo 2TB', 'Almacenamiento portátil con conexión USB-C.', 'Storage', 130, 60),
('Smartwatch', 'Reloj inteligente con monitor de frecuencia cardíaca.', 'Wearables', 250, 40),
('Bocinas Bluetooth', 'Altavoces inalámbricos con sonido envolvente.', 'Audio', 120, 50),
('Cargador Rápido 65W', 'Cargador compatible con USB-C y Power Delivery.', 'Accessories', 45, 80),
('Hub USB-C', 'Adaptador con múltiples puertos USB y HDMI.', 'Accessories', 70, 65),
('Soporte para Monitor', 'Base ajustable para monitor de escritorio.', 'Furniture', 90, 30),
('Lámpara LED de Escritorio', 'Lámpara regulable con luz fría y cálida.', 'Office', 40, 100),
('Mochila para Laptop', 'Mochila resistente con compartimentos acolchados.', 'Accessories', 60, 75),
('Cámara de Seguridad', 'Cámara WiFi con detección de movimiento.', 'Home', 200, 45),
('Kit de Herramientas', 'Set de destornilladores y llaves para reparación.', 'Tools', 50, 90),
('Toner para Impresora', 'Cartucho de tinta negra para impresoras láser.', 'Office', 80, 70),
('Mouse Pad XL', 'Alfombrilla extendida con base antideslizante.', 'Accessories', 25, 120),
('Control de Xbox', 'Mando inalámbrico compatible con PC y consola.', 'Gaming', 70, 55),
('Volante de Carreras', 'Volante con pedales para simuladores de conducción.', 'Gaming', 350, 15),
('Joystick para PC', 'Control para juegos de vuelo y simulación.', 'Gaming', 120, 20),
('Monitor Curvo 32”', 'Monitor con tasa de refresco de 144Hz.', 'Electronics', 400, 25),
('Micrófono Profesional', 'Micrófono de condensador para streaming y podcast.', 'Audio', 150, 40),
('Lentes de Realidad Virtual', 'Gafas VR para experiencias inmersivas.', 'Gaming', 450, 20),
('Teclado Bluetooth', 'Teclado compacto compatible con iOS y Android.', 'Accessories', 80, 70),
('Batería Externa 20000mAh', 'Power bank con carga rápida.', 'Accessories', 60, 85),
('Refrigerador Portátil', 'Mini nevera para viajes y oficina.', 'Home', 300, 15),
('Cafetera Espresso', 'Máquina de café automática con espumador de leche.', 'Home', 220, 30),
('Drone con Cámara 4K', 'Drone con estabilización y grabación de video 4K.', 'Electronics', 500, 10),
('Cinta LED RGB', 'Tira de luces LED con control remoto.', 'Home', 30, 120),
('Mando para Smart TV', 'Control remoto universal compatible con Android TV.', 'Accessories', 20, 90),
('Cerradura Inteligente', 'Cerradura con lector de huellas y WiFi.', 'Home', 250, 15),
('Termo Acero Inoxidable', 'Botella térmica para bebidas frías y calientes.', 'Accessories', 35, 100),
('Reloj Deportivo', 'Reloj resistente al agua con GPS.', 'Wearables', 180, 30),
('Altavoz Inteligente', 'Asistente virtual con altavoces integrados.', 'Home', 100, 40),
('Kit de Iluminación', 'Set de luces LED para fotografía y video.', 'Photography', 180, 25);